use_frameworks!

platform :ios, '10.0'

target 'SlikeRecommendation_Example' do
  pod 'SlikeRecommendation', :path => '../'

  target 'SlikeRecommendation_Tests' do
    inherit! :search_paths

    
  end
end
